"""Kash protocol Python SDK — ``kashdao-protocol-sdk``.

Public surface barrel — mirrors the TypeScript reference's
``src/index.ts`` export shape so consumers can
import the same names regardless of language (modulo ``camelCase`` ↔
``snake_case``).

The SDK ships **two co-equal trading modes**:

- :func:`create_eoa_client` — vanilla EIP-1559 from a plain EOA. The
  canonical Hummingbot path. No bundler, no smart account, no
  ERC-4337 overhead. Bring a private key and an RPC URL.
- :func:`create_smart_account_client` — ERC-4337 v0.7 via SimpleAccount.
  For users on AA stacks (Privy, Coinbase Smart Wallet, Pimlico). Add
  a bundler URL to the EOA shape.

Both modes share the same markets / account-read surface and the same
discriminated ``TradingClient`` union.

This barrel re-exports the full public surface: factories
(``create_eoa_client``, ``create_smart_account_client``), trade
lifecycle methods (build / prepare / send / submit / simulate /
hash_of), bundler clients, signers, on-chain reads, observability
hooks, error catalog, and shared utilities. Internal helpers stay
behind underscored module paths.
"""

from kashdao_protocol_sdk._version import __version__

# ---------------------------------------------------------------------------
# EOA mode — factory + lifecycle (canonical Hummingbot path)
# ---------------------------------------------------------------------------
from kashdao_protocol_sdk.eoa import (
    BuiltTransaction,
    EoaAccount,
    EoaClient,
    EoaClientConfig,
    EoaClientConfigInput,
    EoaMarkets,
    EoaSignerAdapter,
    EoaSubmitOptions,
    EoaSubmitResult,
    EoaTrades,
    EoaTradesSend,
    EoaTxOverrides,
    JsonRpcEoaSigner,
    JsonRpcEoaSignerConfig,
    LocalEoaSigner,
    PrepareEoaFeeOverrides,
    PrepareEoaOptions,
    SendEoaOptions,
    SendEoaResult,
    SendEoaResultFireAndForget,
    SendEoaResultWaited,
    UnsignedTransaction,
    build_approve_transaction,
    build_buy_transaction,
    build_close_position_transaction,
    build_sell_transaction,
    compute_transaction_hash,
    create_eoa_client,
    json_rpc_eoa_signer,
    parse_eoa_client_config,
    prepare_approve_transaction,
    prepare_buy_transaction,
    prepare_close_position_transaction,
    prepare_sell_transaction,
    send_approve_transaction,
    send_buy_transaction,
    send_close_position_transaction,
    send_sell_transaction,
    simulate_transaction,
    submit_transaction,
    viem_account_eoa_signer,
)
from kashdao_protocol_sdk.shared.abortable import abortable_sleep
from kashdao_protocol_sdk.shared.account import (
    MAX_UINT256,
    encode_approve,
    get_gas_balance,
    get_position,
    get_usdc_allowance,
    get_usdc_balance,
    token_id_for,
)

# ---------------------------------------------------------------------------
# Shared mode-agnostic surface
# ---------------------------------------------------------------------------
from kashdao_protocol_sdk.shared.contracts import (
    BASE_MAINNET,
    BASE_SEPOLIA,
    CANONICAL_SMART_ACCOUNT,
    ENTRY_POINT_07_ABI,
    ENTRY_POINT_07_ADDRESS,
    ERC20_ABI,
    ERC1155_OUTCOME_TOKENS_ABI,
    KNOWN_CHAIN_IDS,
    MARKET_ABI,
    MARKET_FACTORY_ABI,
    MULTICALL3_ABI,
    MULTICALL3_ADDRESS,
    ORACLE_ABI,
    PARAM_REGISTRY_ABI,
    SIMPLE_ACCOUNT_ABI,
    SIMPLE_ACCOUNT_FACTORY_ABI,
    SUPPORTED_CHAIN_IDS,
    VAULT_ABI,
    ProtocolAddresses,
    get_protocol_addresses,
    is_known_chain_id,
    is_supported_chain_id,
)
from kashdao_protocol_sdk.shared.contracts.addresses import SmartAccountConfig
from kashdao_protocol_sdk.shared.contracts.decoders import decode_market_revert
from kashdao_protocol_sdk.shared.custom_chain import (
    CustomChain,
    CustomChainAddresses,
    CustomSmartAccountConfig,
    resolve_custom_chain,
)
from kashdao_protocol_sdk.shared.error_codes import ErrorCode
from kashdao_protocol_sdk.shared.errors import (
    KashAbortedError,
    KashBundlerError,
    KashChainError,
    KashConfigError,
    KashProtocolError,
    KashSignerError,
    KashSimulationRevertedError,
    KashTransactionExpiredError,
    KashTransactionOutcomeUnknownError,
    KashValidationError,
    throw_if_aborted,
    to_kash_aborted,
)
from kashdao_protocol_sdk.shared.fees import (
    EstimateFeesOptions,
    FeeEstimate,
    estimate_chain_fees,
)
from kashdao_protocol_sdk.shared.hooks import (
    BundlerErrorEvent,
    BundlerRequestEvent,
    BundlerResponseEvent,
    EoaWaitOrphanedEvent,
    KashProtocolHooks,
    SignerErrorEvent,
    SignerKind,
    SignerRequestEvent,
    SmartAccountWaitOrphanedEvent,
    WaitOrphanedEvent,
)
from kashdao_protocol_sdk.shared.instrumented_signer import (
    instrument_eoa_signer,
    instrument_smart_account_signer,
)
from kashdao_protocol_sdk.shared.json_rpc import JsonRpcError, JsonRpcResponse
from kashdao_protocol_sdk.shared.markets import (
    QuoteParams,
    WatchConnectionState,
    WatchEvent,
    WatchOptions,
    WatchSubscription,
    get_market_minimal,
    get_market_state,
    get_quote,
    watch_market,
)
from kashdao_protocol_sdk.shared.retry import RetryOptions, with_retry
from kashdao_protocol_sdk.shared.rpc_health import (
    ChainRpcHealth,
    ChainRpcHealthError,
    ChainRpcHealthOk,
    check_chain_rpc_health,
)
from kashdao_protocol_sdk.shared.trading_client import (
    TradingClient,
    is_eoa_client,
    is_smart_account_client,
)
from kashdao_protocol_sdk.shared.types import (
    BuildApproveParams,
    BuildBuyParams,
    BuildClosePositionParams,
    BuildSellParams,
    Hex,
    MarketIdentity,
    MarketOutcomeState,
    MarketState,
    MarketStatus,
    MinimalMarketRead,
    OutcomePosition,
    Position,
    Quote,
    QuoteSide,
    SimulationDecodedError,
    SimulationFailure,
    SimulationResult,
    SimulationSuccess,
)
from kashdao_protocol_sdk.shared.units import (
    TOKEN_DECIMALS,
    USDC_DECIMALS,
    format_tokens,
    format_usdc,
    tokens,
    usdc,
)

# ---------------------------------------------------------------------------
# Smart Account mode — full surface (bundler clients, account derivation,
# trades pipeline, signers, client factory). Mirrors the TS reference's
# ``smart-account/`` subtree.
# ---------------------------------------------------------------------------
from kashdao_protocol_sdk.smart_account import (
    AlchemyBundlerConfig,
    BundlerCallOptions,
    BundlerClient,
    BundlerClientConfig,
    BundlerOptions,
    ComputeSmartAccountAddressParams,
    FlashbotsBundlerConfig,
    JsonRpcSigner,
    JsonRpcSignerConfig,
    LocalSigner,
    PaymasterConfig,
    PimlicoBundlerConfig,
    PrepareUserOpOptions,
    SmartAccountAccount,
    SmartAccountClient,
    SmartAccountClientConfig,
    SmartAccountClientConfigInput,
    SmartAccountMarkets,
    SmartAccountTrades,
    SmartAccountTradesSend,
    build_approve_user_op,
    build_buy_user_op,
    build_close_position_user_op,
    build_sell_user_op,
    compute_smart_account_address,
    compute_smart_account_address_via_web3,
    compute_user_op_hash,
    create_alchemy_bundler_client,
    create_flashbots_bundler_client,
    create_generic_bundler_client,
    create_pimlico_bundler_client,
    create_smart_account_client,
    encode_create_account,
    is_smart_account_deployed,
    json_rpc_signer,
    parse_smart_account_client_config,
    prepare_approve_user_op,
    prepare_buy_user_op,
    prepare_close_position_user_op,
    prepare_sell_user_op,
    send_approve_user_op,
    send_buy_user_op,
    send_close_position_user_op,
    send_sell_user_op,
    simulate_user_op,
    submit_user_op,
    user_op_to_typed_data,
    viem_account_signer,
)
from kashdao_protocol_sdk.smart_account.types import (
    BuildOptions,
    BuiltUserOp,
    BundlerHealth,
    BundlerHealthError,
    BundlerHealthOk,
    GasEstimate,
    GasOverrides,
    PrepareFeeOverrides,
    SendResult,
    SendResultFireAndForget,
    SendResultWaited,
    SignedUserOp,
    SignerAdapter,
    SmartAccountSignerAdapter,
    SubmitOptions,
    SubmitResult,
    UnsignedUserOp,
    UserOpReceipt,
    UserOpTypedData,
)

__all__ = [
    "__version__",
    # Shared — addresses + canonical constants
    "BASE_MAINNET",
    "BASE_SEPOLIA",
    "CANONICAL_SMART_ACCOUNT",
    "ENTRY_POINT_07_ABI",
    "ENTRY_POINT_07_ADDRESS",
    "ERC1155_OUTCOME_TOKENS_ABI",
    "ERC20_ABI",
    "KNOWN_CHAIN_IDS",
    "MARKET_ABI",
    "MARKET_FACTORY_ABI",
    "MULTICALL3_ABI",
    "MULTICALL3_ADDRESS",
    "ORACLE_ABI",
    "PARAM_REGISTRY_ABI",
    "ProtocolAddresses",
    "SIMPLE_ACCOUNT_ABI",
    "SIMPLE_ACCOUNT_FACTORY_ABI",
    "SUPPORTED_CHAIN_IDS",
    "SmartAccountConfig",
    "VAULT_ABI",
    "get_protocol_addresses",
    "is_known_chain_id",
    "is_supported_chain_id",
    # Shared — errors
    "KashAbortedError",
    "KashBundlerError",
    "KashChainError",
    "KashConfigError",
    "KashProtocolError",
    "KashSignerError",
    "KashSimulationRevertedError",
    "KashTransactionExpiredError",
    "KashTransactionOutcomeUnknownError",
    "KashValidationError",
    # Shared — trade input + market types
    "BuildApproveParams",
    "BuildBuyParams",
    "BuildClosePositionParams",
    "BuildSellParams",
    "Hex",
    "MarketIdentity",
    "MarketOutcomeState",
    "MarketState",
    "MarketStatus",
    "MinimalMarketRead",
    "OutcomePosition",
    "Position",
    "Quote",
    "QuoteSide",
    "SimulationDecodedError",
    "SimulationFailure",
    "SimulationResult",
    "SimulationSuccess",
    # Shared — account reads
    "MAX_UINT256",
    "encode_approve",
    "get_gas_balance",
    "get_position",
    "get_usdc_allowance",
    "get_usdc_balance",
    "token_id_for",
    # Shared — markets reads
    "QuoteParams",
    "WatchConnectionState",
    "WatchEvent",
    "WatchOptions",
    "WatchSubscription",
    "get_market_minimal",
    "get_market_state",
    "get_quote",
    "watch_market",
    # Shared — fees, retry, units, hooks, decoders
    "EstimateFeesOptions",
    "FeeEstimate",
    "estimate_chain_fees",
    "RetryOptions",
    "with_retry",
    "BundlerErrorEvent",
    "BundlerRequestEvent",
    "BundlerResponseEvent",
    "EoaWaitOrphanedEvent",
    "KashProtocolHooks",
    "SignerErrorEvent",
    "SignerKind",
    "SignerRequestEvent",
    "SmartAccountWaitOrphanedEvent",
    "WaitOrphanedEvent",
    # Shared — error code catalog
    "ErrorCode",
    # Shared — abort + RPC health + JSON-RPC envelope
    "abortable_sleep",
    "ChainRpcHealth",
    "ChainRpcHealthError",
    "ChainRpcHealthOk",
    "check_chain_rpc_health",
    "JsonRpcError",
    "JsonRpcResponse",
    # Shared — instrumented signer wrappers
    "instrument_eoa_signer",
    "instrument_smart_account_signer",
    "TOKEN_DECIMALS",
    "USDC_DECIMALS",
    "format_tokens",
    "format_usdc",
    "tokens",
    "usdc",
    "decode_market_revert",
    # Shared — custom chain
    "CustomChain",
    "CustomChainAddresses",
    "CustomSmartAccountConfig",
    "resolve_custom_chain",
    # Shared — trading-client union
    "TradingClient",
    "is_eoa_client",
    "is_smart_account_client",
    # Shared — abort helpers
    "throw_if_aborted",
    "to_kash_aborted",
    # EOA mode — factory + signers + types + lifecycle functions
    "BuiltTransaction",
    "EoaAccount",
    "EoaClient",
    "EoaClientConfig",
    "EoaClientConfigInput",
    "EoaMarkets",
    "EoaSignerAdapter",
    "EoaSubmitOptions",
    "EoaSubmitResult",
    "EoaTrades",
    "EoaTradesSend",
    "EoaTxOverrides",
    "JsonRpcEoaSigner",
    "JsonRpcEoaSignerConfig",
    "LocalEoaSigner",
    "PrepareEoaFeeOverrides",
    "PrepareEoaOptions",
    "SendEoaOptions",
    "SendEoaResult",
    "SendEoaResultFireAndForget",
    "SendEoaResultWaited",
    "UnsignedTransaction",
    "build_approve_transaction",
    "build_buy_transaction",
    "build_close_position_transaction",
    "build_sell_transaction",
    "compute_transaction_hash",
    "create_eoa_client",
    "json_rpc_eoa_signer",
    "parse_eoa_client_config",
    "prepare_approve_transaction",
    "prepare_buy_transaction",
    "prepare_close_position_transaction",
    "prepare_sell_transaction",
    "send_approve_transaction",
    "send_buy_transaction",
    "send_close_position_transaction",
    "send_sell_transaction",
    "simulate_transaction",
    "submit_transaction",
    "viem_account_eoa_signer",
    # Smart Account mode — full ERC-4337 v0.7 surface.
    "AlchemyBundlerConfig",
    "BuildOptions",
    "BuiltUserOp",
    "BundlerCallOptions",
    "BundlerClient",
    "BundlerClientConfig",
    "ComputeSmartAccountAddressParams",
    "BundlerHealth",
    "BundlerHealthError",
    "BundlerHealthOk",
    "FlashbotsBundlerConfig",
    "GasEstimate",
    "GasOverrides",
    "PimlicoBundlerConfig",
    "PrepareFeeOverrides",
    "SendResult",
    "SendResultFireAndForget",
    "SendResultWaited",
    "SignedUserOp",
    "SignerAdapter",
    "SmartAccountClient",
    "SmartAccountSignerAdapter",
    "SubmitOptions",
    "SubmitResult",
    "UnsignedUserOp",
    "UserOpReceipt",
    "UserOpTypedData",
    "BundlerOptions",
    "JsonRpcSigner",
    "JsonRpcSignerConfig",
    "LocalSigner",
    "PaymasterConfig",
    "PrepareUserOpOptions",
    "SmartAccountAccount",
    "SmartAccountClientConfig",
    "SmartAccountClientConfigInput",
    "SmartAccountMarkets",
    "SmartAccountTrades",
    "SmartAccountTradesSend",
    "build_approve_user_op",
    "build_buy_user_op",
    "build_close_position_user_op",
    "build_sell_user_op",
    "compute_smart_account_address",
    "compute_smart_account_address_via_web3",
    "compute_user_op_hash",
    "create_alchemy_bundler_client",
    "create_flashbots_bundler_client",
    "create_generic_bundler_client",
    "create_pimlico_bundler_client",
    "create_smart_account_client",
    "encode_create_account",
    "is_smart_account_deployed",
    "json_rpc_signer",
    "parse_smart_account_client_config",
    "prepare_approve_user_op",
    "prepare_buy_user_op",
    "prepare_close_position_user_op",
    "prepare_sell_user_op",
    "send_approve_user_op",
    "send_buy_user_op",
    "send_close_position_user_op",
    "send_sell_user_op",
    "simulate_user_op",
    "submit_user_op",
    "user_op_to_typed_data",
    "viem_account_signer",
]
