"""Canonical UserOp hashing — EIP-4337 v0.7.

Mirrors ``src/smart-account/trades/hash.ts``.

Centralised here so the build path, the submit-side staleness check,
and the public ``client.trades.hash_of()`` accessor all agree on the
exact hash the bundler / EntryPoint will compute. Drift between any
two of these would silently corrupt signed UserOps (the AA24 trap).

The TS version delegates to ``viem.getUserOperationHash``; the Python
port implements the EIP-4337 v0.7 hash directly using ``eth-abi`` +
``eth-utils``. The two implementations target byte-identical output
against a shared parity-fixture set generated by the TS side; that
fixture suite lands as a separate cross-language sweep (tracked in
``tests/parity/test_user_op_hash_parity.py``). The local
``test_sa_hash.py`` covers determinism + per-field sensitivity but
does NOT pin the canonical bytes against viem.

The EntryPoint v0.7 UserOp hash is::

    accountGasLimits = uint128(verificationGasLimit) || uint128(callGasLimit)
    gasFees          = uint128(maxPriorityFeePerGas) || uint128(maxFeePerGas)
    initCode         = factory(20) || factoryData    (or empty)
    paymasterAndData = paymaster(20) || verifGasLimit(16) || postOpGasLimit(16) || data
                       (or empty)

    packed = abi.encode(
      address sender,
      uint256 nonce,
      bytes32 keccak(initCode),
      bytes32 keccak(callData),
      bytes32 accountGasLimits,
      uint256 preVerificationGas,
      bytes32 gasFees,
      bytes32 keccak(paymasterAndData),
    )

    userOpHash = keccak(abi.encode(
      bytes32 keccak(packed),
      address entryPoint,
      uint256 chainId,
    ))
"""

from __future__ import annotations

from typing import Any

from eth_abi import encode as abi_encode  # type: ignore[attr-defined]
from eth_utils import keccak, to_bytes  # type: ignore[attr-defined]
from hexbytes import HexBytes

from kashdao_protocol_sdk.shared.types import Hex
from kashdao_protocol_sdk.smart_account.types import UnsignedUserOp, UserOpTypedData


def compute_user_op_hash(
    chain_id: int,
    entry_point_address: Hex,
    user_op: UnsignedUserOp,
) -> Hex:
    """Compute the canonical EIP-4337 v0.7 UserOp hash.

    This is what the EntryPoint contract computes during validation,
    and therefore what the consumer's signer must sign over. After
    populating gas + fee fields on a :class:`UnsignedUserOp`, callers
    MUST recompute the hash with this function before signing — the
    build-time hash on :class:`BuiltUserOp` is stale once gas is
    filled in.

    ``entry_point_address`` is chain-resolved via the registry on
    supported chains and via :class:`CustomChain.smart_account` on
    custom chains — never re-import :data:`ENTRY_POINT_07_ADDRESS`
    directly here so Anvil deployments with non-canonical EntryPoint
    addresses keep working.
    """
    init_code = _init_code(user_op)
    paymaster_and_data = _paymaster_and_data(user_op)
    account_gas_limits = _pack_uint128_pair(user_op.verification_gas_limit, user_op.call_gas_limit)
    gas_fees = _pack_uint128_pair(user_op.max_priority_fee_per_gas, user_op.max_fee_per_gas)

    packed = abi_encode(
        [
            "address",
            "uint256",
            "bytes32",
            "bytes32",
            "bytes32",
            "uint256",
            "bytes32",
            "bytes32",
        ],
        [
            user_op.sender,
            user_op.nonce,
            keccak(init_code),
            keccak(_hex_to_bytes(user_op.call_data)),
            account_gas_limits,
            user_op.pre_verification_gas,
            gas_fees,
            keccak(paymaster_and_data),
        ],
    )

    digest = keccak(
        abi_encode(
            ["bytes32", "address", "uint256"],
            [keccak(packed), entry_point_address, chain_id],
        )
    )
    return HexBytes(digest).to_0x_hex()


def user_op_to_typed_data(
    chain_id: int,
    entry_point_address: Hex,
    user_op: UnsignedUserOp,
) -> UserOpTypedData:
    """EIP-712 typed-data view of a UserOp.

    Input shape for signers that prefer ``eth_signTypedData_v4`` over
    raw-hash signing (Fireblocks workspace policies, certain AWS-KMS
    wrappers, etc.).

    This MUST match the typed-data structure the EntryPoint v0.7
    verification code accepts. As of EntryPoint v0.7, only the raw-hash
    path is universally supported by ``SimpleAccount.validateUserOp``;
    the typed-data path is for advanced consumers whose signer-side
    infrastructure can produce signatures the EntryPoint's verification
    accepts.
    """
    return UserOpTypedData(
        domain={
            "name": "ERC4337",
            "version": "0.7.0",
            "chainId": chain_id,
            "verifyingContract": entry_point_address,
        },
        types={
            "PackedUserOperation": [
                {"name": "sender", "type": "address"},
                {"name": "nonce", "type": "uint256"},
                {"name": "callData", "type": "bytes"},
                {"name": "callGasLimit", "type": "uint256"},
                {"name": "verificationGasLimit", "type": "uint256"},
                {"name": "preVerificationGas", "type": "uint256"},
                {"name": "maxFeePerGas", "type": "uint256"},
                {"name": "maxPriorityFeePerGas", "type": "uint256"},
            ],
        },
        primaryType="PackedUserOperation",
        message=user_op,
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _init_code(user_op: UnsignedUserOp) -> bytes:
    """``factory || factoryData`` (or empty when undeployed isn't requested)."""
    if not user_op.factory or not user_op.factory_data:
        return b""
    return _hex_to_bytes(user_op.factory) + _hex_to_bytes(user_op.factory_data)


def _paymaster_and_data(user_op: UnsignedUserOp) -> bytes:
    """``paymaster || verifGasLimit(16) || postOpGasLimit(16) || data`` (or empty)."""
    if not user_op.paymaster:
        return b""
    paymaster_bytes = _hex_to_bytes(user_op.paymaster)
    verif = (user_op.paymaster_verification_gas_limit or 0).to_bytes(16, "big")
    post = (user_op.paymaster_post_op_gas_limit or 0).to_bytes(16, "big")
    data = _hex_to_bytes(user_op.paymaster_data) if user_op.paymaster_data else b""
    return paymaster_bytes + verif + post + data


def _pack_uint128_pair(high: int, low: int) -> bytes:
    """Pack ``high(16) || low(16)`` into a 32-byte word.

    Used for ``accountGasLimits`` (verif | call) and ``gasFees``
    (priority | max). The first arg is the more-significant half per
    the EntryPoint v0.7 layout.
    """
    if high < 0 or high >= 2**128:
        raise ValueError(f"uint128 high out of range: {high}")
    if low < 0 or low >= 2**128:
        raise ValueError(f"uint128 low out of range: {low}")
    return high.to_bytes(16, "big") + low.to_bytes(16, "big")


def _hex_to_bytes(value: Any) -> bytes:
    """Coerce a hex-string-or-bytes into raw bytes.

    Accepts ``"0x..."``, ``HexBytes(...)``, or raw ``bytes``. ``"0x"``
    is the empty bytes string.
    """
    if isinstance(value, bytes):
        return bytes(value)
    if isinstance(value, str):
        if value == "" or value == "0x":
            return b""
        return to_bytes(hexstr=value)
    raise TypeError(f"expected hex string or bytes, got {type(value).__name__}")


__all__ = ["compute_user_op_hash", "user_op_to_typed_data"]
