"""Exact-integer parity between the curve port and the SVM Python reference model.

``fixtures/curve-parity.jsonl`` is ``@kashdao/pythag-math``'s corpus,
generated by driving the protocol's reference model
(``SVM/tests/support/reference_model``) over fixed grids — the same corpus the
TypeScript ``kash-curve.parity.test.ts`` and the TS SDK's quote-parity test
run against. Every field is compared as an exact integer; a refusal must raise
with the model's own error code. There is no tolerance: a one-unit
disagreement is a wrong quote on a money path.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from kashdao_protocol_sdk.solana import KashValidationError, curve

CORPUS = Path(__file__).parent / "fixtures" / "curve-parity.jsonl"
VECTORS: list[dict[str, Any]] = [
    json.loads(line) for line in CORPUS.read_text("utf-8").splitlines() if line.strip()
]


def _big(value: Any) -> int:
    return int(value)


def _bigs(values: Any) -> list[int]:
    return [int(v) for v in values]


def _enc(value: Any) -> Any:
    if isinstance(value, bool) or value is None:
        return value
    if isinstance(value, int):
        return str(value)
    if isinstance(value, (list, tuple)):
        return [_enc(v) for v in value]
    if isinstance(value, dict):
        return {k: _enc(v) for k, v in value.items()}
    return value


def _market_to_reference(m: curve.CurveMarket) -> dict[str, Any]:
    return {
        "supplies": [str(s) for s in m.supplies],
        "reserve": str(m.reserve),
        "aggregate": str(m.aggregate),
        "genesis_leg_wad": str(m.genesis_leg_wad),
        "genesis_unharvested": str(m.genesis_unharvested),
        "balance_usdc": str(m.balance_usdc),
        "fees_usdc": str(m.fees_usdc),
        "volume_wad": str(m.volume_wad),
        "fee_bps": str(m.fee_bps),
        "status": m.status,
        "snapshot": (
            {
                "reserve": str(m.snapshot.reserve),
                "aggregate": str(m.snapshot.aggregate),
                "supplies": [str(s) for s in m.snapshot.supplies],
            }
            if m.snapshot is not None
            else None
        ),
        "winning_outcome": None if m.winning_outcome is None else str(m.winning_outcome),
        "winning_supply": str(m.winning_supply),
    }


def _buy_quote(q: curve.BuyQuote) -> dict[str, int]:
    return {
        "quote_aggregate": q.quote_aggregate,
        "discriminant": q.discriminant,
        "tokens_wad": q.tokens_wad,
    }


def _sell_quote(q: curve.SellQuote) -> dict[str, int]:
    return {
        "quote_aggregate": q.quote_aggregate,
        "release_wad": q.release_wad,
        "net_wad": q.net_wad,
    }


def _trace(v: dict[str, Any]) -> list[Any]:
    a = v["args"]
    m = curve.genesis(int(a["n"]), _big(a["raw_seed"]))
    out: list[Any] = [{"state": _market_to_reference(m)}]
    for step in v.get("steps", []):
        s = step["args"]
        op = step["op"]
        if op == "buy":
            bought = curve.buy(m, int(s["outcome"]), _big(s["gross_usdc"]))
            m = bought.market
            out.append({"state": _market_to_reference(m), "outputs": [_buy_quote(bought.quote)]})
        elif op == "sell":
            sold = curve.sell(m, int(s["outcome"]), _big(s["tokens_wad"]))
            m = sold.market
            out.append(
                {
                    "state": _market_to_reference(m),
                    "outputs": [_sell_quote(sold.quote), sold.net_usdc],
                }
            )
        elif op in ("claim", "collect_fees"):
            paid = (
                curve.claim(m, int(s["outcome"]), _big(s["tokens_wad"]))
                if op == "claim"
                else curve.collect_fees(m)
            )
            m = paid.market
            out.append(
                {
                    "state": _market_to_reference(m),
                    "outputs": [
                        {"usdc": paid.payout.usdc, "reserve_after": paid.payout.reserve_after}
                    ],
                }
            )
        elif op == "cancel":
            m = curve.cancel(m)
            out.append({"state": _market_to_reference(m)})
        elif op == "resolve":
            m = curve.resolve(m, int(s["outcome"]))
            out.append({"state": _market_to_reference(m)})
        else:
            raise AssertionError(f"unhandled trace op {op}")
    return out


def _evaluate(v: dict[str, Any]) -> Any:
    a = v["args"]
    op = v["op"]
    if op == "weight":
        return curve.weight(int(a["n"]), int(a["outcome"]))
    if op == "seed_wad":
        return curve.seed_wad(_big(a["raw_seed"]))
    if op == "protocol_fee":
        if "fee_bps" in a:
            return curve.protocol_fee(_big(a["amount_usdc"]), _big(a["fee_bps"]))
        return curve.protocol_fee(_big(a["amount_usdc"]))
    if op == "to_usdc":
        return curve.to_usdc(_big(a["wad"]))
    if op == "aggregate":
        return curve.aggregate(_bigs(a["supplies"]))
    if op == "capital_shares":
        return curve.capital_shares(_bigs(a["supplies"]))
    if op == "mul_div":
        return curve.mul_div(_big(a["left"]), _big(a["right"]), _big(a["divisor"]))
    if op == "root":
        return curve.root(_big(a["value"]))
    if op == "term":
        return curve.term(_big(a["coefficient"]), _big(a["supply"]))
    if op == "liquidity_coefficient":
        return curve.liquidity_coefficient(_big(a["reserve"]), _big(a["total"]))
    if op == "marginal_price":
        return curve.marginal_price(
            _big(a["reserve"]), _big(a["total"]), _big(a["coefficient"]), _big(a["supply"])
        )
    if op == "replace_term":
        return curve.replace_term(
            _big(a["total"]), _big(a["coefficient"]), _big(a["before"]), _big(a["after"])
        )
    if op == "buy_quote":
        return _buy_quote(
            curve.buy_quote(
                _big(a["total"]),
                _big(a["reserve"]),
                _big(a["coefficient"]),
                _big(a["supply"]),
                _big(a["input_wad"]),
            )
        )
    if op == "sell_quote":
        args = [
            _big(a["total"]),
            _big(a["reserve"]),
            _big(a["coefficient"]),
            _big(a["supply"]),
            _big(a["tokens_wad"]),
        ]
        if "sell_fee_bps" in a:
            args.append(_big(a["sell_fee_bps"]))
        return _sell_quote(curve.sell_quote(*args))
    if op == "redemption_wad":
        return curve.redemption_wad(
            _big(a["reserve"]), _big(a["tokens_wad"]), _big(a["winning_supply"])
        )
    if op == "resolved_payout":
        p = curve.resolved_payout(
            _big(a["reserve"]),
            _big(a["tokens_wad"]),
            _big(a["winning_supply"]),
            _big(a["balance_usdc"]),
            _big(a["fees_usdc"]),
        )
        return {"usdc": p.usdc, "reserve_after": p.reserve_after}
    if op == "trace":
        return _trace(v)
    raise AssertionError(f"unhandled op {op}")


def test_the_corpus_covers_every_op_and_some_refusals() -> None:
    assert len(VECTORS) >= 200
    ops = {v["op"] for v in VECTORS}
    for op in (
        "weight",
        "seed_wad",
        "protocol_fee",
        "to_usdc",
        "aggregate",
        "capital_shares",
        "redemption_wad",
        "resolved_payout",
        "buy_quote",
        "sell_quote",
        "marginal_price",
        "trace",
    ):
        assert op in ops, op
    assert sum(1 for v in VECTORS if v["op"] == "buy_quote") > 30
    assert sum(1 for v in VECTORS if v["op"] == "sell_quote") > 30
    assert sum(1 for v in VECTORS if v["expected"]["ok"]) > 150
    assert sum(1 for v in VECTORS if not v["expected"]["ok"]) >= 8


@pytest.mark.parametrize("vector", VECTORS, ids=[f"{i}-{v['op']}" for i, v in enumerate(VECTORS)])
def test_vector_matches_the_reference_model_exactly(vector: dict[str, Any]) -> None:
    expected = vector["expected"]
    if expected["ok"]:
        assert _enc(_evaluate(vector)) == expected["result"]
    else:
        with pytest.raises(KashValidationError) as exc:
            _evaluate(vector)
        assert exc.value.program_error == expected["error"]["code"]
